# -*- coding: utf-8 -*-

# logging
logging: /home/sdanioth/Documents/git/oscar-catalogue/logging/

# source file
# FacilitySource: /home/zue/users/sdanioth/Documents/Praktikum/git/oscar/oscar-catalogue/example-facility-catalogue_base.json
# ObservationSource: /home/zue/users/sdanioth/Documents/Praktikum/git/oscar/oscar-catalogue/example-observation-catalogue.yaml
FacilitySource: /home/sdanioth/Documents/git/oscar-catalogue/example-facility-catalogue_base.json
ObservationSource: /home/sdanioth/Documents/git/oscar-catalogue/example-observation-catalogue.yaml
InstrumentSource: /home/sdanioth/Documents/git/oscar-catalogue/example-instrument-catalogue.csv


# target file
# FacilityTarget: /home/zue/users/sdanioth/Documents/Praktikum/git/oscar/oscar-catalogue/oscar-facility-catalogue/
# ObervatonTarget: /home/zue/users/sdanioth/Documents/Praktikum/git/oscar/oscar-catalogue/oscar-observation-catalogue/
FacilityTarget: /home/sdanioth/Documents/git/oscar-catalogue/oscar-facility-catalogue/
ObervatonTarget: /home/sdanioth/Documents/git/oscar-catalogue/oscar-observation-catalogue/
InstrumentTarget: /home/sdanioth/Documents/git/oscar-catalogue/oscar-instrument-catalogue/


# jinja2 template
FacilityTemplate: facility-catalogue-template_base.xml
ObservationTemplate: observation-catalogue-template.xml
InstrumentTemplate: instrument-catalogue-template.xml

# variables that need to get the WMDR Codes Registry notation (from dictionaries)
variablesWMDR:
- "ObservedVariableAtmosphere"
- "Geometry"
- "WMORegion"
- "FacilityType"
- "ProgramAffiliation"
- "TerritoryName"
- "GeopositioningMethod"
- "ReportingStatus"

variablesWMDR_obs:
- "ObservedVariableAtmosphere"
- "Geometry"
- "ProgramAffiliation"
- "ObservingMethodAtmosphere"
- "SourceOfObservation"
- "samplingStrategy"
- "ScheduleStartWeekday"
- "ScheduleEndWeekday"
- "ScheduleStartMonth"
- "ScheduleEndMonth"

variablesWMDR_ins:
- "ObservedVariableAtmosphere"

# header information
individualName: Sarina Danioth
organisationName: MeteoSwiss
electronicMailAddress: sarina.danioth@meteoswiss.ch

# API endpoints
upload: https://oscardepl.wmo.int/surface/rest/api/wmd/upload/
#upload: https://oscar.wmo.int/surface/rest/api/wmd/upload/

# proxies
proxies : {"http": "http://here-goes-the-proxy-address:port-number",
           "https": "https://here-goes-the-proxy-address:port-number"}

# security token
token: 'b5cc647b-21c2-4cbd-b0a4-d9d141db42c5'
