# -*- coding: utf-8 -*-

# logging
logging: /home/zue/users/sdanioth/Documents/Praktikum/git/oscar/oscar-catalogue/logging/

# source file
FacilitySource: "/home/zue/users/sdanioth/Documents/Praktikum/git/oscar/oscar-catalogue/example-facility-catalogue_base.json"
ObservationSource: /home/zue/users/sdanioth/Documents/Praktikum/git/oscar/oscar-catalogue/example-observation-catalogue.json

# target file
FacilityTarget: /home/zue/users/sdanioth/Documents/Praktikum/git/oscar/oscar-catalogue/oscar-facility-catalogue/
ObervatonTarget: /home/zue/users/sdanioth/Documents/Praktikum/git/oscar/oscar-catalogue/oscar-observation-catalogue/

# jinja2 template
FacilityTemplate: facility-catalogue-template_base.xml
ObservationTemplate: observation-catalogue-template.xml

# variables that need to get the WMDR Codes Registry notation (from dictionaries)
variablesWMDR:
- "ObservedVariableAtmosphere"
- "Geometry"
- "WMORegion"
- "FacilityType"
- "ProgramAffiliation"
- "TerritoryName"
- "GeopositioningMethod"
- "ReportingStatus"

variablesWMDR_obs:
- "ObservedVariableAtmosphere"
- "Geometry"
- "ProgramAffiliation"
- "ObservingMethodAtmosphere"
- "SourceOfObservation"
- "samplingStrategy"
- "ScheduleStartWeekday"
- "ScheduleEndWeekday"
- "ScheduleStartMonth"
- "ScheduleEndMonth"

# header information
individualName: Sarina Danioth
organisationName: MeteoSwiss
electronicMailAddress: sarina.danioth@meteoswiss.ch

# API endpoints
upload: https://oscardepl.wmo.int/surface/rest/api/wmd/upload/
#upload: https://oscar.wmo.int/surface/rest/api/wmd/upload/

# proxies
proxies : {"http": "http://here-goes-the-proxy-address:port-number",
           "https": "https://here-goes-the-proxy-address:port-number"}

# security token
token: 'a8f9d57e-5fe0-426f-94cf-223ba61d0833'
