# -*- coding: utf-8 -*-

# logging
logging: /home/sdanioth/Documents/git/oscar-facility-catalogue/logging/

# source file
#FacilitySource: /home/sdanioth/Documents/git/oscar-catalogue/example-facility-catalogue_base.csv
FacilitySource: /home/sdanioth/Documents/git/oscar-catalogue/KADI_TEST_SURVEY.csv
ObservationSource: /home/sdanioth/Documents/git/oscar-catalogue/example-observation-catalogue.csv

# target file
FacilityTarget: /home/sdanioth/Documents/git/oscar-catalogue/oscar-facility-catalogue/
ObervatonTarget: /home/sdanioth/Documents/git/oscar-catalogue/oscar-observation-catalogue/

# jinja2 template
FacilityTemplate: facility-catalogue-template_base.xml
ObservationTemplate: observation-catalogue-template.xml

# header information
individualName: Sarina Danioth
organisationName: MeteoSwiss
electronicMailAddress: sarina.danioth@meteoswiss.ch

# API endpoints
upload: https://oscardepl.wmo.int/surface/rest/api/wmd/upload/
#upload: https://oscar.wmo.int/surface/rest/api/wmd/upload/

# proxies
proxies : {"http": "http://here-goes-the-proxy-address:port-number",
           "https": "https://here-goes-the-proxy-address:port-number"}

# security token
token: 'bea1a424-eee9-4edc-8467-c5b9497d2a6c'
