# -*- coding: utf-8 -*-

# logging
logging: ../oscar-catalogue/logging/

# source file
# FacilitySource: ../oscar/oscar-catalogue/example-facility-catalogue_base.json
# ObservationSource: ../oscar/oscar-catalogue/example-observation-catalogue.yaml
FacilitySource: ../oscar-catalogue/example-facility-catalogue_base.json
ObservationSource: ../oscar-catalogue/example-observation-catalogue.yaml
InstrumentSource: ../oscar-catalogue/example-instrument-catalogue.csv


# target file
# FacilityTarget: ../oscar/oscar-catalogue/oscar-facility-catalogue/
# ObervatonTarget: ../oscar/oscar-catalogue/oscar-observation-catalogue/
FacilityTarget: ../oscar-catalogue/oscar-facility-catalogue/
ObervatonTarget: ../oscar-catalogue/oscar-observation-catalogue/
InstrumentTarget: ../oscar-catalogue/oscar-instrument-catalogue/


# jinja2 template
FacilityTemplate: facility-catalogue-template_base.xml
ObservationTemplate: observation-catalogue-template.xml
InstrumentTemplate: instrument-catalogue-template.xml

# variables that need to get the WMDR Codes Registry notation (from dictionaries)
variablesWMDR:
- "ObservedVariableAtmosphere"
- "Geometry"
- "WMORegion"
- "FacilityType"
- "ProgramAffiliation"
- "TerritoryName"
- "GeopositioningMethod"
- "ReportingStatus"

variablesWMDR_obs:
- "ObservedVariableAtmosphere"
- "Geometry"
- "ProgramAffiliation"
- "ObservingMethodAtmosphere"
- "SourceOfObservation"
- "samplingStrategy"
- "ScheduleStartWeekday"
- "ScheduleEndWeekday"
- "ScheduleStartMonth"
- "ScheduleEndMonth"

variablesWMDR_ins:
- "ObservedVariableAtmosphere"

# header information
individualName: Sarina Danioth
organisationName: MeteoSwiss
electronicMailAddress: sarina.danioth@meteoswiss.ch

# API endpoints
upload: https://oscardepl.wmo.int/surface/rest/api/wmd/upload/
#upload: https://oscar.wmo.int/surface/rest/api/wmd/upload/

# proxies
proxies : {"http": "http://here-goes-the-proxy-address:port-number",
           "https": "https://here-goes-the-proxy-address:port-number"}

# security token - for DEPL: mus be renewed weekly
token: '61d1c002-7d8a-4fcc-9100-85b1c6b6b2e3'
