# -*- coding: utf-8 -*-

# logging
logging: ~/Public/git/oscar-facility-catalogue/logging/

# source file
source: ~/Public/git/oscar-facility-catalogue/example-facility-catalogue.csv

# target file
target: ~/Public/git/oscar-facility-catalogue/

# jinja2 template
template: facility-catalogue-template.xml

# header information
individualName: Sarina Danioth
organisationName: MeteoSwiss
electronicMailAddress: sarina.danioth@meteoswiss.ch

# API endpoints
upload: https://oscardepl.wmo.int/surface/rest/api/wmd/upload/
#upload: https://oscar.wmo.int/surface/rest/api/wmd/upload/

# proxies
proxies : {"http": "http://here-goes-the-proxy-address:port-number",
           "https": "https://here-goes-the-proxy-address:port-number"}

# security token
token: none
